# Data prep

Este notebook é dedicado ao data prep e exportação de um csv com os dados trabalhados ('diabetic_data_df.csv') e as colunas utilizadas ('col2use.csv')

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time

In [2]:
# load the csv file
df = pd.read_csv('diabetic_data.csv')

## Algumas análises

In [3]:
print('Number of samples:',len(df))

Number of samples: 101766


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
encounter_id                101766 non-null int64
patient_nbr                 101766 non-null int64
race                        101766 non-null object
gender                      101766 non-null object
age                         101766 non-null object
weight                      101766 non-null object
admission_type_id           101766 non-null int64
discharge_disposition_id    101766 non-null int64
admission_source_id         101766 non-null int64
time_in_hospital            101766 non-null int64
payer_code                  101766 non-null object
medical_specialty           101766 non-null object
num_lab_procedures          101766 non-null int64
num_procedures              101766 non-null int64
num_medications             101766 non-null int64
number_outpatient           101766 non-null int64
number_emergency            101766 non-null int64
number_inpatient            10176

In [5]:
df.head()

encounter_id  patient_nbr             race  gender      age weight  \
0       2278392      8222157        Caucasian  Female   [0-10)      ?   
1        149190     55629189        Caucasian  Female  [10-20)      ?   
2         64410     86047875  AfricanAmerican  Female  [20-30)      ?   
3        500364     82442376        Caucasian    Male  [30-40)      ?   
4         16680     42519267        Caucasian    Male  [40-50)      ?   

   admission_type_id  discharge_disposition_id  admission_source_id  \
0                  6                        25                    1   
1                  1                         1                    7   
2                  1                         1                    7   
3                  1                         1                    7   
4                  1                         1                    7   

   time_in_hospital  ... citoglipton insulin  glyburide-metformin  \
0                 1  ...          No      No                   No   
1                 3  ...          No      Up                   No   
2                 2  ...          No      No                   No   
3                 2  ...          No      Up                   No   
4                 1  ...          No  Steady                   No   

   glipizide-metformin  glimepiride-pioglitazone  metformin-rosiglitazone  \
0                   No                        No                       No   
1                   No                        No                       No   
2                   No                        No                       No   
3                   No                        No                       No   
4                   No                        No                       No   

   metformin-pioglitazone  change diabetesMed readmitted  
0                      No      No          No         NO  
1                      No      Ch         Yes        >30  
2                      No      No         Yes         NO  
3                      No      Ch         Yes         NO  
4                      No      Ch         Yes         NO  

[5 rows x 50 columns]

In [6]:
# count the number of rows for each type
df.groupby('readmitted').size()

readmitted
<30    11357
>30    35545
NO     54864
dtype: int64

In [7]:
# discharge_disposition_id, tells us where the patient went after the hospitalization.
df.groupby('discharge_disposition_id').size()

discharge_disposition_id
1     60234
2      2128
3     13954
4       815
5      1184
6     12902
7       623
8       108
9        21
10        6
11     1642
12        3
13      399
14      372
15       63
16       11
17       14
18     3691
19        8
20        2
22     1993
23      412
24       48
25      989
27        5
28      139
dtype: int64

In [8]:
#visualização de 10 em 10 colunas
df[list(df.columns)[:10]].head()

encounter_id  patient_nbr             race  gender      age weight  \
0       2278392      8222157        Caucasian  Female   [0-10)      ?   
1        149190     55629189        Caucasian  Female  [10-20)      ?   
2         64410     86047875  AfricanAmerican  Female  [20-30)      ?   
3        500364     82442376        Caucasian    Male  [30-40)      ?   
4         16680     42519267        Caucasian    Male  [40-50)      ?   

   admission_type_id  discharge_disposition_id  admission_source_id  \
0                  6                        25                    1   
1                  1                         1                    7   
2                  1                         1                    7   
3                  1                         1                    7   
4                  1                         1                    7   

   time_in_hospital  
0                 1  
1                 3  
2                 2  
3                 2  
4                 1

In [9]:
#visualização de 10 em 10 colunas
df[list(df.columns)[10:20]].head()

payer_code         medical_specialty  num_lab_procedures  num_procedures  \
0          ?  Pediatrics-Endocrinology                  41               0   
1          ?                         ?                  59               0   
2          ?                         ?                  11               5   
3          ?                         ?                  44               1   
4          ?                         ?                  51               0   

   num_medications  number_outpatient  number_emergency  number_inpatient  \
0                1                  0                 0                 0   
1               18                  0                 0                 0   
2               13                  2                 0                 1   
3               16                  0                 0                 0   
4                8                  0                 0                 0   

   diag_1  diag_2  
0  250.83       ?  
1     276  250.01  
2     648     250  
3       8  250.43  
4     197     157

In [10]:
#visualização de 10 em 10 colunas
df[list(df.columns)[20:30]].head()

diag_3  number_diagnoses max_glu_serum A1Cresult metformin repaglinide  \
0      ?                 1          None      None        No          No   
1    255                 9          None      None        No          No   
2    V27                 6          None      None        No          No   
3    403                 7          None      None        No          No   
4    250                 5          None      None        No          No   

  nateglinide chlorpropamide glimepiride acetohexamide  
0          No             No          No            No  
1          No             No          No            No  
2          No             No          No            No  
3          No             No          No            No  
4          No             No          No            No

In [11]:
#visualização de 10 em 10 colunas
df[list(df.columns)[30:40]].head()

glipizide glyburide tolbutamide pioglitazone rosiglitazone acarbose  \
0        No        No          No           No            No       No   
1        No        No          No           No            No       No   
2    Steady        No          No           No            No       No   
3        No        No          No           No            No       No   
4    Steady        No          No           No            No       No   

  miglitol troglitazone tolazamide examide  
0       No           No         No      No  
1       No           No         No      No  
2       No           No         No      No  
3       No           No         No      No  
4       No           No         No      No

In [12]:
#visualização de 10 em 10 colunas
df[list(df.columns)[40:]].head()

citoglipton insulin glyburide-metformin glipizide-metformin  \
0          No      No                  No                  No   
1          No      Up                  No                  No   
2          No      No                  No                  No   
3          No      Up                  No                  No   
4          No  Steady                  No                  No   

  glimepiride-pioglitazone metformin-rosiglitazone metformin-pioglitazone  \
0                       No                      No                     No   
1                       No                      No                     No   
2                       No                      No                     No   
3                       No                      No                     No   
4                       No                      No                     No   

  change diabetesMed readmitted  
0     No          No         NO  
1     Ch         Yes        >30  
2     No         Yes         NO  
3     Ch         Yes         NO  
4     Ch         Yes         NO

In [13]:
# Mostra os IDs unicos da base se forem (em quantidade) menores que 30, caso contrário diz quantos são
# for each column
for c in list(df.columns):
    
    # get a list of unique values
    n = df[c].unique()
    
    # if number of unique values is less than 30, print the values. Otherwise print the number of unique values
    if len(n)<30:
        print(c)
        print(n)
    else:
        print(c + ': ' +str(len(n)) + ' unique values')

encounter_id: 101766 unique values
patient_nbr: 71518 unique values
race
['Caucasian' 'AfricanAmerican' '?' 'Other' 'Asian' 'Hispanic']
gender
['Female' 'Male' 'Unknown/Invalid']
age
['[0-10)' '[10-20)' '[20-30)' '[30-40)' '[40-50)' '[50-60)' '[60-70)'
 '[70-80)' '[80-90)' '[90-100)']
weight
['?' '[75-100)' '[50-75)' '[0-25)' '[100-125)' '[25-50)' '[125-150)'
 '[175-200)' '[150-175)' '>200']
admission_type_id
[6 1 2 3 4 5 8 7]
discharge_disposition_id
[25  1  3  6  2  5 11  7 10  4 14 18  8 13 12 16 17 22 23  9 20 15 24 28
 19 27]
admission_source_id
[ 1  7  2  4  5  6 20  3 17  8  9 14 10 22 11 25 13]
time_in_hospital
[ 1  3  2  4  5 13 12  9  7 10  6 11  8 14]
payer_code
['?' 'MC' 'MD' 'HM' 'UN' 'BC' 'SP' 'CP' 'SI' 'DM' 'CM' 'CH' 'PO' 'WC' 'OT'
 'OG' 'MP' 'FR']
medical_specialty: 73 unique values
num_lab_procedures: 118 unique values
num_procedures
[0 5 1 6 2 3 4]
num_medications: 75 unique values
number_outpatient: 39 unique values
number_emergency: 33 unique values
number_inpatient

## Trabalhando a base

In [14]:
# De acordo com IDs_mapping.csv os IDs 11,13,14,19,20,21 são relacionados a morte ou hospício. Remover esses IDs do modelo.
df = df.loc[~df.discharge_disposition_id.isin([11,13,14,19,20,21])]

In [15]:
# Criando a coluna de output para classificação binária
df['OUTPUT_LABEL'] = (df.readmitted == '<30').astype('int')

In [16]:
# replace ? with nan
df = df.replace('?',np.nan)

In [17]:
# nas colunas 'race', 'player_code' e 'medical_specialty' estao faltando dados, preencher com 'UNK'
df['race'] = df['race'].fillna('UNK')
df['payer_code'] = df['payer_code'].fillna('UNK')
df['medical_specialty'] = df['medical_specialty'].fillna('UNK')

In [18]:
# Sobre a coluna 'medical_specialty', pega os top 10 mais recorrentes e cria uma nova coluna contendo somente estes top 10
# os outros dados que não estão dentro dos top 10 são classificados como 'Other'
top_10 = ['UNK','InternalMedicine','Emergency/Trauma',\
          'Family/GeneralPractice', 'Cardiology','Surgery-General' ,\
          'Nephrology','Orthopedics',\
          'Orthopedics-Reconstructive','Radiologist']

# make a new column with duplicated data
df['med_spec'] = df['medical_specialty'].copy()

# replace all specialties not in top 10 with 'Other' category
df.loc[~df.med_spec.isin(top_10),'med_spec'] = 'Other'

To convert our categorical features to numbers, we will use a technique called one-hot encoding. In one-hot encoding, you create a new column for each unique value in that column. Then the value of the column is 1 if the sample has that unique value or 0 otherwise. For example, for the column race, we would create new columns ('race_Caucasian','race_AfricanAmerican', etc). If the patient's race is Caucasian, the patient gets a 1 under 'race_Caucasian' and 0 under the rest of the race columns. To create these one-hot encoding columns, we can use the get_dummies function.

Now the problem is that if we create a column for each unique value, we have correlated columns. In other words, the value in one column can be figured out by looking at the rest of the columns. For example, if the sample is not AfricanAmerican, Asian, Causasian, Hispance or Other, it must be UNK. To deal with this, we can use the drop_first option, which will drop the first categorical value for each column.

The get_dummies function does not work on numerical data. To trick get_dummies, we can convert the numerical data into strings and then it will work properly.

In [19]:
cols_cat = ['race', 'gender', 
       'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed','payer_code']

cols_cat_num = ['admission_type_id', 'discharge_disposition_id', 'admission_source_id']

df[cols_cat_num] = df[cols_cat_num].astype('str')

df_cat = pd.get_dummies(df[cols_cat + cols_cat_num + ['med_spec']],drop_first = True)

df = pd.concat([df,df_cat], axis = 1)

# salva as colunas de dados categóricos em 'cols_all_cat'
cols_all_cat = list(df_cat.columns)

In [20]:
# transformação das colunas de idade e peso de categóricas para numéricas
age_id = {'[0-10)':0, 
          '[10-20)':10, 
          '[20-30)':20, 
          '[30-40)':30, 
          '[40-50)':40, 
          '[50-60)':50,
          '[60-70)':60, 
          '[70-80)':70, 
          '[80-90)':80, 
          '[90-100)':90}
df['age_group'] = df.age.replace(age_id)

df['has_weight'] = df.weight.notnull().astype('int')

# salva as colunas 'age_group' e 'has_weight'
cols_extra = ['age_group','has_weight']

In [21]:
cols_num = ['time_in_hospital','num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient','number_diagnoses']

In [22]:
# cria o df_data que é o dataframe final com os dados utilizados
col2use = cols_num + cols_all_cat + cols_extra
col2use_df = pd.DataFrame(list(col2use), columns=['col2use'])
col2use_df.to_csv('col2use.csv')

df_data = df[col2use + ['OUTPUT_LABEL']]

In [23]:
# exporta csv do dataframe final
df_data.to_csv(path_or_buf="diabetic_data_df.csv", index=False)

In [24]:
df_data.head()

time_in_hospital  num_lab_procedures  num_procedures  num_medications  \
0                 1                  41               0                1   
1                 3                  59               0               18   
2                 2                  11               5               13   
3                 2                  44               1               16   
4                 1                  51               0                8   

   number_outpatient  number_emergency  number_inpatient  number_diagnoses  \
0                  0                 0                 0                 1   
1                  0                 0                 0                 9   
2                  2                 0                 1                 6   
3                  0                 0                 0                 7   
4                  0                 0                 0                 5   

   race_Asian  race_Caucasian  ...  med_spec_Nephrology  med_spec_Orthopedics  \
0           0               1  ...                    0                     0   
1           0               1  ...                    0                     0   
2           0               0  ...                    0                     0   
3           0               1  ...                    0                     0   
4           0               1  ...                    0                     0   

   med_spec_Orthopedics-Reconstructive  med_spec_Other  med_spec_Radiologist  \
0                                    0               1                     0   
1                                    0               0                     0   
2                                    0               0                     0   
3                                    0               0                     0   
4                                    0               0                     0   

   med_spec_Surgery-General  med_spec_UNK  age_group  has_weight  OUTPUT_LABEL  
0                         0             0          0           0             0  
1                         0             1         10           0             0  
2                         0             1         20           0             0  
3                         0             1         30           0             0  
4                         0             1         40           0             0  

[5 rows x 144 columns]